[tool.mypy]
python_version="3.11"
exclude = ['venv', '.venv', 'env', '.env']

[tool.pytest.ini_options]
addopts = "--tb=line -s -v -p no:cacheprovider"
env = [
    "OPEN_WEATHER_API_KEY={{OPEN_WEATHER_API_KEY}}"
]