name: Python linters and tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install mypy and pytest
        run: |
          python -m pip install --upgrade pip
          pip install mypy
          mypy --install-types --non-interactive
          pip install pytest pytest-env
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with mypy
        run: |
          mypy .
      - name: Test with pytest
        run: |
          pytest ./tests
