name: Python linters and tests

# on: [push, pull_request]
on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install mypy and pytest
        run: |
          python -m pip install --upgrade pip
          pip install mypy pytest
      - name: Lint with mypy
        run: |
          mypy .
      - name: Test with pytest
        run: |
          pytest ./tests
